<a href="https://www.kaggle.com/code/mohanasriharan/data-science-job-salary-prediction?scriptVersionId=107198350" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd
from sklearn.tree import DecisionTreeRegressor# data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/agencyperformance/finalapi.csv
/kaggle/input/data-science-job-salaries/ds_salaries.csv

In [2]:
df=pd.read_csv("/kaggle/input/data-science-job-salaries/ds_salaries.csv")

In [3]:
df.head()

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L

In [4]:
df.shape

(607, 12)

In [5]:
df.isna().sum()

Unnamed: 0            0
work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
dtype: int64

In [6]:
df.corr()

               Unnamed: 0  work_year    salary  salary_in_usd  remote_ratio
Unnamed: 0       1.000000   0.886550 -0.096250       0.167025      0.095000
work_year        0.886550   1.000000 -0.087577       0.170493      0.076314
salary          -0.096250  -0.087577  1.000000      -0.083906     -0.014608
salary_in_usd    0.167025   0.170493 -0.083906       1.000000      0.132122
remote_ratio     0.095000   0.076314 -0.014608       0.132122      1.000000

In [7]:
df.drop(['employee_residence'],axis=1,inplace=True)

In [8]:
df.drop(['remote_ratio'],axis=1,inplace=True)

In [9]:
df.drop(['company_size'],axis=1,inplace=True)

In [10]:
df.drop(['employment_type'],axis=1,inplace=True)

In [11]:
df.drop(['company_location'],axis=1,inplace=True)

In [12]:
df.drop(['salary_in_usd'],axis=1,inplace=True)

In [13]:
df.head()
df.shape

(607, 6)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 607 entries, 0 to 606
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        607 non-null    int64
 1   work_year         607 non-null    int64
 2   experience_level  607 non-null    object
 3   job_title         607 non-null    object
 4   salary            607 non-null    int64
 5   salary_currency   607 non-null    object
dtypes: int64(3), object(3)
memory usage: 28.6+ KB

In [15]:
import keras

In [16]:
X=pd.get_dummies(df)

In [17]:
X = X.drop(columns=['salary'])

In [18]:
X.head()

,Unnamed: 0,work_year,experience_level_EN,experience_level_EX,experience_level_MI,experience_level_SE,job_title_3D Computer Vision Researcher,job_title_AI Scientist,job_title_Analytics Engineer,job_title_Applied Data Scientist,...,salary_currency_EUR,salary_currency_GBP,salary_currency_HUF,salary_currency_INR,salary_currency_JPY,salary_currency_MXN,salary_currency_PLN,salary_currency_SGD,salary_currency_TRY,salary_currency_USD
0,0,2020,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1,1,2020,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,2,2020,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,3,2020,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,4,2020,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [19]:
Y = df[['salary']]

In [20]:
from sklearn import linear_model
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.30, random_state = 10)

In [22]:
reg = DecisionTreeRegressor()
reg.fit(X,Y)

DecisionTreeRegressor()

In [23]:
y_pred = reg.predict(X_test)

In [24]:
y_pred

array([8.000000e+04, 7.200000e+05, 2.087750e+05, 6.000000e+05,
       9.315000e+04, 5.000000e+04, 1.640000e+05, 4.500000e+04,
       5.400000e+04, 4.200000e+04, 1.470000e+05, 1.241900e+05,
       1.090000e+05, 9.032000e+04, 4.090000e+04, 2.160000e+04,
       1.400000e+05, 4.000000e+04, 3.000000e+04, 2.500000e+05,
       1.350000e+05, 1.740000e+05, 1.470000e+05, 1.150000e+05,
       1.500000e+05, 1.400000e+05, 3.000000e+05, 8.000000e+04,
       4.500000e+05, 9.500000e+04, 7.000000e+04, 8.000000e+04,
       1.000000e+05, 1.450000e+06, 1.350000e+05, 1.400000e+04,
       1.120000e+05, 4.500000e+05, 5.700000e+04, 1.260000e+05,
       4.500000e+04, 2.153000e+05, 1.350000e+05, 1.159340e+05,
       1.751000e+05, 1.350000e+05, 5.000000e+04, 7.000000e+04,
       6.000000e+04, 1.129000e+05, 1.050000e+05, 2.184400e+04,
       1.150000e+05, 1.048900e+05, 1.062600e+05, 8.000000e+04,
       5.000000e+04, 1.500000e+05, 2.140000e+05, 2.300000e+05,
       1.100000e+05, 4.450000e+06, 5.500000e+04, 6.500000e+04,
       1.250000e+06, 7.500000e+04, 6.900000e+04, 2.664000e+05,
       8.000000e+04, 6.130000e+04, 1.500000e+05, 1.050000e+05,
       2.500000e+05, 9.032000e+04, 7.676000e+04, 4.000000e+04,
       1.924000e+05, 1.880000e+05, 1.130000e+05, 1.649960e+05,
       2.700000e+05, 2.100000e+04, 5.400000e+04, 8.000000e+04,
       9.500000e+04, 5.900000e+04, 1.060000e+05, 9.000000e+04,
       1.100000e+07, 5.500000e+04, 3.745600e+04, 1.020000e+05,
       1.300000e+05, 8.000000e+04, 1.230000e+05, 6.000000e+04,
       2.100000e+05, 2.500000e+04, 2.300000e+05, 6.000000e+04,
       1.100000e+07, 1.500000e+05, 7.500000e+04, 1.678750e+05,
       4.230000e+05, 2.000000e+05, 8.800000e+04, 1.900000e+05,
       5.000000e+04, 7.676000e+04, 3.000000e+04, 2.420000e+05,
       6.000000e+04, 1.799997e+06, 1.000000e+05, 1.700000e+05,
       2.350000e+05, 2.100000e+06, 4.800000e+04, 5.800000e+04,
       9.370000e+04, 7.000000e+06, 1.760000e+05, 1.201600e+05,
       5.250000e+04, 3.500000e+04, 2.600000e+05, 1.300000e+05,
       1.021000e+05, 9.900000e+04, 2.250000e+06, 5.000000e+04,
       1.440000e+05, 1.460000e+05, 2.000000e+04, 1.851000e+05,
       9.370000e+04, 2.560000e+05, 4.000000e+03, 3.400000e+04,
       1.205000e+05, 9.900000e+04, 1.150000e+05, 2.000000e+05,
       5.300000e+04, 9.000000e+04, 3.000000e+04, 4.500000e+04,
       1.800000e+04, 1.300000e+05, 2.900000e+04, 1.008000e+05,
       1.520000e+05, 1.450000e+05, 6.500000e+04, 3.000000e+04,
       2.200000e+06, 8.500000e+04, 1.800000e+05, 9.000000e+04,
       6.700000e+04, 1.440000e+05, 1.700000e+05, 1.129000e+05,
       3.800000e+05, 6.500000e+04, 6.650000e+04, 3.840000e+04,
       2.001000e+05, 1.770000e+05, 1.740000e+05, 1.300000e+05,
       7.000000e+04, 1.350000e+05, 8.000000e+04, 1.100000e+05,
       2.000000e+04, 2.000000e+05, 1.200000e+05, 6.000000e+06,
       1.600800e+05, 9.936000e+04, 5.300000e+04])

In [25]:
r2_score = reg.score(X_test,y_test)
print(r2_score*100,'%')

100.0 %